import Link from 'next/link';
import {Book} from '@/lib/data';
import {FavoriteButton} from './FavoriteButton';
<<<<<<< HEAD
export function CoverArt({book,small=false}:{book:Book;small?:boolean}){return <div className={`relative flex shrink-0 items-end overflow-hidden rounded-[14px] ${small?'h-14 w-12':'h-48 w-36 sm:h-56 sm:w-40'}`} style={{background:`linear-gradient(140deg,${book.cover} 0%,${book.cover} 58%,${book.accent} 100%)`}}><div className="absolute -right-5 -top-8 h-28 w-28 rounded-full border border-white/20"/><div className="absolute bottom-0 left-0 h-1/2 w-full bg-gradient-to-t from-black/30 to-transparent"/>{!small&&<div aria-hidden="true" className="relative z-10 p-4 text-white"><div className="mb-8 text-[10px] font-bold uppercase tracking-[.2em] text-white/70">বই কথা</div><div className="serif line-clamp-4 text-xl leading-[1.05] sm:text-2xl">{book.title}</div><div className="mt-2 line-clamp-1 text-[10px] text-white/80">{book.author}</div></div>}</div>}
=======
export function CoverArt({book,small=false}:{book:Book;small?:boolean}){return <div className={`relative flex shrink-0 items-end overflow-hidden rounded-[14px] ${small?'h-14 w-12':'h-48 w-36 sm:h-56 sm:w-40'}`} style={{background:`linear-gradient(140deg,${book.cover} 0%,${book.cover} 58%,${book.accent} 100%)`}}><div className="absolute -right-5 -top-8 h-28 w-28 rounded-full border border-white/20"/><div className="absolute bottom-0 left-0 h-1/2 w-full bg-gradient-to-t from-black/30 to-transparent"/>{!small&&<div className="relative z-10 p-4 text-white"><div className="mb-8 text-[10px] font-bold uppercase tracking-[.2em] text-white/70">বই কথা</div><div className="serif text-xl leading-[1.05] sm:text-2xl">{book.title}</div><div className="mt-2 text-[10px] text-white/80">{book.author}</div></div>}</div>}
>>>>>>> 2ab7aa76f7999d2438f175506db4e436eba6a695
export function BookCard({book,favorited=false}:{book:Book;favorited?:boolean}){return <div className="relative min-w-[150px] sm:min-w-[168px]"><Link href={`/books/${book.id}`} className="group block"><div className="relative transition-transform duration-200 group-hover:-translate-y-1"><CoverArt book={book}/></div><div className="mt-3"><h3 className="truncate text-[15px] font-bold">{book.title}</h3><p className="mt-1 truncate text-xs text-[var(--muted)]">{book.author}</p><div className="mt-2 flex items-center gap-2 text-[11px] text-[var(--muted)]"><span>{book.duration}</span><span className="h-1 w-1 rounded-full bg-[var(--amber)]"/><span>{book.genre}</span></div></div></Link><FavoriteButton bookId={book.id} initialFavorited={favorited} className="absolute right-2 top-2 z-10"/></div>}
